# Generated by Django 3.2.25 on 2025-09-26 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speed_kmh', models.FloatField()),
                ('Acceleration_ms2', models.FloatField()),
                ('Battery_State', models.FloatField()),
                ('Driving_Mode', models.CharField(max_length=50)),
                ('Road_Type', models.CharField(max_length=50)),
                ('Traffic_Condition', models.CharField(max_length=50)),
                ('Weather_Condition', models.CharField(max_length=50)),
                ('Humidity', models.FloatField()),
                ('Wind_Speed', models.FloatField()),
                ('Vehicle_Weight', models.FloatField()),
                ('Distance_Travelled', models.FloatField()),
                ('Predicted_Energy', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
