# Generated by Django 3.2.25 on 2025-09-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_evprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userregistrationmodel'),
        ),
    ]
