# Generated by Django 3.2.25 on 2025-09-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_evprediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evprediction',
            name='timestamp',
        ),
    ]
