# Generated by Django 3.2.25 on 2025-09-26 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_evprediction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='evprediction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
